
notifications:
  email: false

git:
  depth: 3
  
env: 
  global:
    - pyv=2.7

matrix:
  include:
    - os: osx
      env: 
        - osv=MacOSX

    - os: linux
      env: 
        - osv=Linux

install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-$osv-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes --quiet conda
    - conda create --yes -n test python=$pyv
    - source activate test
    - pip -q install coveralls
    - python setup.py develop
#    - conda install --yes scipy=0.16.1 #patch for library travis
    
script:
    - coverage run Test/test.py

after_success:
    - coveralls
